### ISSUE TITLE
Question about external app code methods

### ISSUE THREAD

**Issue by albertososa95** [DudaDev/react-widget-demo#2]
Hello,
I'm building a widget using React as external widget development framework. The [documentation](https://developer.duda.co/docs/external-js-apps#external-app-code) says that I should expose `init()` and `clean()` methods with these signatures:
```javascript
export function init({ container, props, ...additionalData }) {
  // render you app into `container`, passing it `props` if needed
}

export function clean() {
  // cleanup for the app
}
```

In your example, the methods signatures aren't the same. 
1) What is the purpose of `clean()` method? 
2) When does it called in Duda website life-cycle? 

I think that documentation is not enough to understanding it.

Sincerely,
Alberto.

**Comment by liady** [comment]
@albertososa95 good catch, thanks. The functions' signatures are now matching the documentation.
As per the "clean" method - it is supposed to be called when transitioning between pages without refresh. (It is currently not called - but is important to implement it for future support)
